version: '3.8'

services:
  pinn:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - CONFIG_DIR=/app/config
      - MODEL_DIR=/app/models
      - LOG_DIR=/app/logs
      - DATA_DIR=/app/data
      - PYTHONPATH=/app
    command: python -m src.cli.train --help

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/app/notebooks
      - ./config:/app/config
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - CONFIG_DIR=/app/config
      - MODEL_DIR=/app/models
      - LOG_DIR=/app/logs
      - DATA_DIR=/app/data
      - PYTHONPATH=/app
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
      - ./config:/app/config
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - CONFIG_DIR=/app/config
      - MODEL_DIR=/app/models
      - LOG_DIR=/app/logs
      - DATA_DIR=/app/data
      - PYTHONPATH=/app
    command: pytest tests/ -v --cov=src 