# Power Grid PINN Configuration

# Model Architecture
model:
  layers: [4, 64, 64, 64, 2]  # Input: [v_mag, v_ang, p_inj, q_inj], Output: [v_mag, v_ang]
  activation: "tanh"
  learning_rate: 0.001
  batch_size: 32

# Grid Parameters
grid:
  bus_count: 14  # IEEE 14-bus system
  line_count: 20
  base_mva: 100.0
  voltage_limits:
    min: 0.95
    max: 1.05
  line_limits:
    thermal_limit: 1.0  # per unit

# Training Parameters
training:
  epochs: 5000
  physics_weight: 1.0
  data_weight: 1.0
  validation_split: 0.2
  early_stopping_patience: 50

# Data Parameters
data:
  input_features:
    - voltage_magnitude
    - voltage_angle
    - active_power
    - reactive_power
  output_features:
    - voltage_magnitude
    - voltage_angle
  normalization: "minmax"  # or "standard"

# Optimization Parameters
optimization:
  objective: "minimize_losses"  # or "maximize_stability"
  constraints:
    - "voltage_limits"
    - "line_flow_limits"
    - "power_balance"
  solver: "adam"
  max_iterations: 1000
  convergence_tolerance: 1e-6 